import cv2
import matplotlib.pyplot as plt
img=cv2.imread("f://PERSONAL/pic image.jpeg")
grey_img=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
invert_img=cv2.bitwise_not(grey_img)
blur_img=cv2.GaussianBlur(invert_img,(111,111),0)
invert_img=cv2.bitwise_not(grey_img)
sketch_img=cv2.divide(grey_img,blur_img,scale=256.0)
cv2.imwrite("sketch.png",sketch_img)
cv2.imshow('sketch image',sketch_img)
cv2.waitKey(0)
cv2.destroyAllWindows()
plt.figure(figsize(14,8))
plt.Subplot(1,2,1)
plt.title("original image",18)
plt.imshow(RGB_img)
plt.axix("off")
plt.subplot(1,2,2)
plt.title("sketch",size=18)
rgb_sketch=cv2.cvtColor(sketch_img,cv2.COLOR_BGR2RGB)
plt.imshow(rgb_sketch)
plt.axis("off")
plt.show()
